### ISSUE TITLE
PHP Error: Call to a member function tokenAuth() on array

### ISSUE THREAD

**Issue by wandrien** [bludit/bludit#1456]
```
GET /admin/content - Uncaught Error: Call to a member function tokenAuth() on array in /home/vadim/bludit-test/bl-kernel/login.class.php:169
Stack trace:
#0 /home/vadim/bludit-test/bl-kernel/admin/controllers/login.php(53): Login->verifyUserByRemember()
#1 /home/vadim/bludit-test/bl-kernel/admin/controllers/login.php(67): checkRememberMe()
#2 /home/vadim/bludit-test/bl-kernel/boot/admin.php(97): include('/home/vadim/blu...')
#3 /home/vadim/bludit-test/index.php(37): require('/home/vadim/blu...')
#4 {main}
  thrown in /home/vadim/bludit-test/bl-kernel/login.class.php on line 169
```

### Bludit version
The latest from git (55d3b162bf745298637741beb75600439f1ee2a9)

**Comment by geekless** [comment]
I fixed it in this way on my installation. Just pasted a few lines from verifyUser(). Not sure if it is 100% correct.

```diff
diff --git a/bl-kernel/login.class.php b/bl-kernel/login.class.php
index bb86952d..992278a6 100644
--- a/bl-kernel/login.class.php
+++ b/bl-kernel/login.class.php
@@ -164,8 +164,12 @@ class Login {
         }
 
         // Get user from database and login
-        $user = $this->users->getUserDB($username);
-        $this->setLogin($username, $user['role'], $user->tokenAuth());
+        try {
+            $user = new User($username);
+        } catch (Exception $e) {
+            return false;
+        }
+        $this->setLogin($username, $user->role(), $user->tokenAuth());
         Log::set(__METHOD__.LOG_SEP.'User authenticated via Remember Me.');
         return true;
     }
```
