### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by guleyc** [bludit/bludit#1550]
I can't upload any image to my new posts. PHP Error log is below. 
<img width="840" alt="Screenshot 2023-12-06 at 21 48 52" src="https://github.com/bludit/bludit/assets/18706339/9daf2ddd-a0d2-4164-b02c-749ea84f34a8">

### Bludit version
3.15.0

### PHP version
8.2

### PHP logs
```
[06-Dec-2023 21:40:38 Europe/Istanbul] /home/DOMAIN/htdocs/DOMAIN.com/bl-content/uploads/pages/4ccdfb2fa13f95a6e82c0aa980cebb70/thumbnails/*.*
[06-Dec-2023 21:40:38 Europe/Istanbul] PHP Warning:  Undefined variable $codesampleConfig in /home/DOMAIN/htdocs/DOMAIN.com/bl-plugins/tinymce/plugin.php on line 146
[06-Dec-2023 21:40:55 Europe/Istanbul] [INFO] [3.15.0] [/admin/ajax/upload-images] mv /tmp/phpD3Bg1H /home/DOMAIN/htdocs/DOMAIN.com/bl-content/tmp/Double-Exponential-Smoothing-768x197.png
[06-Dec-2023 21:40:55 Europe/Istanbul] PHP Warning:  rename(/tmp/phpD3Bg1H,/home/DOMAIN/htdocs/DOMAIN.com/bl-content/tmp/Double-Exponential-Smoothing-768x197.png): No such file or directory in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/filesystem.class.php on line 68
[06-Dec-2023 21:40:55 Europe/Istanbul] [INFO] [3.15.0] [/admin/ajax/upload-images] mv /home/DOMAIN/htdocs/DOMAIN.com/bl-content/tmp/Double-Exponential-Smoothing-768x197.png /home/DOMAIN/htdocs/DOMAIN.com/bl-content/uploads/pages/4ccdfb2fa13f95a6e82c0aa980cebb70/Double-Exponential-Smoothing-768x197.png
[06-Dec-2023 21:40:55 Europe/Istanbul] PHP Warning:  rename(/home/DOMAIN/htdocs/DOMAIN.com/bl-content/tmp/Double-Exponential-Smoothing-768x197.png,/home/DOMAIN/htdocs/DOMAIN.com/bl-content/uploads/pages/4ccdfb2fa13f95a6e82c0aa980cebb70/Double-Exponential-Smoothing-768x197.png): No such file or directory in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/filesystem.class.php on line 68
[06-Dec-2023 21:40:55 Europe/Istanbul] PHP Warning:  chmod(): No such file or directory in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/functions.php on line 931
[06-Dec-2023 21:40:55 Europe/Istanbul] PHP Warning:  imagecreatefrompng(/home/DOMAIN/htdocs/DOMAIN.com/bl-content/uploads/pages/4ccdfb2fa13f95a6e82c0aa980cebb70/Double-Exponential-Smoothing-768x197.png): Failed to open stream: No such file or directory in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/image.class.php on line 89
[06-Dec-2023 21:40:55 Europe/Istanbul] PHP Fatal error:  Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, bool given in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/image.class.php:16
Stack trace:
#0 /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/image.class.php(16): imagesx()
#1 /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/functions.php(939): Image->setImage()
#2 /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/ajax/upload-images.php(80): transformImage()
#3 /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/boot/admin.php(50): include('...')
#4 /home/DOMAIN/htdocs/DOMAIN.com/index.php(38): require('...')
#5 {main}
  thrown in /home/DOMAIN/htdocs/DOMAIN.com/bl-kernel/helpers/image.class.php on line 16
```

**Comment by dignajar** [comment]
Looks like your webserver is not allowing you to upload files, then the script fails because no file was uploaded. can you post what you have in `Admin > About > Bludit Developers`
