### ISSUE TITLE
admin (and all other redirections) not exist on built-in php server

### ISSUE THREAD

**Issue by Martin-Fox** [bludit/bludit#1581]
### Describe your problem
I had a problem with redirection to /admin so I decided to test on build-in php server, as it was not working for me on lighttpd/nginx/apache2

### Steps to reproduce the problem
$ git clone https://github.com/bludit/bludit.git
$ cd bludit
$ php -S 192.168.1.15:80

visit http://192.168.1.15 => select language, set password, click install, get information "_Congratulations you have successfully installed your Bludit_" and when try to go to dashboard get  http 500

### Bludit version
3.16.2

### PHP version
8.2

### PHP logs
[Mon Sep 23 17:16:19 2024] PHP Fatal error:  Uncaught Error: Call to undefined function session_get_cookie_params() in /root/bludit/bl-kernel/helpers/session.class.php:17
Stack trace:
#0 /root/bludit/bl-kernel/boot/admin.php(5): Session::start()
#1 /root/bludit/index.php(37): require('...')
#2 {main}
  thrown in /root/bludit/bl-kernel/helpers/session.class.php on line 17
[Mon Sep 23 17:16:19 2024] 192.168.1.4:36112 [500]: GET /admin/ - Uncaught Error: Call to undefined function session_get_cookie_params() in /root/bludit/bl-kernel/helpers/session.class.php:17
Stack trace:
#0 /root/bludit/bl-kernel/boot/admin.php(5): Session::start()
#1 /root/bludit/index.php(37): require('...')
#2 {main}
  thrown in /root/bludit/bl-kernel/helpers/session.class.php on line 17
[Mon Sep 23 17:16:19 2024] 192.168.1.4:36112 Closing

**Comment by Martin-Fox** [comment]
Is this project still maintained?

**Comment by dignajar** [comment]
Fixed in version 3.18.0. Please do not hesitate to reopen the ticket if you encounter any further issues. Thank you for taking the time to report this problem.
