### ISSUE TITLE
Error in new installation by viewing content

### ISSUE THREAD

**Issue by freaknils** [bludit/bludit#569]
On a new blank installation of version 2.0.2 I get the following error by clicking _/admin/content_

```
Fatal error: Uncaught Error: Call to a member function key() on boolean in
.../bl-kernel/admin/views/content.php:53 Stack trace:
#0 .../bl-kernel/admin/views/content.php(69): table('static', 'thumb-tack')
#1.../bl-kernel/admin/themes/default/index.php(146): include('/usr/share/weba...')
#2 .../bl-kernel/boot/admin.php(86): include('/usr/share/weba...')
#3 .../index.php(34): require('/usr/share/weba...')
#4 {main} thrown in .../bl-kernel/admin/views/content.php on line 53
```
(Links shortened)

There is just the default content.
Any idears why?

```
: ~  > php --version
PHP 7.1.12 (cli) (built: Nov 22 2017 17:43:08) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies
```
Thanks!

**Comment by clickwork-git** [comment]
I will try an installation with PHP 7.1. Never done before.

What server do you use?

**Comment by freaknils** [comment]
It is a actual archlinux installation.

```
: ~> nginx -v
nginx version: nginx/1.13.6

```

**Comment by freaknils** [comment]
I just tested by using php56

```
: ~ > php56 --version
PHP 5.6.32 (cli) (built: Nov 30 2017 10:51:17) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

But it's the same error:
```
Fatal error: Call to a member function key() on boolean in /usr/share/webapps/bludit/bl-kernel/admin/views/content.php on line 53
```

**Comment by clickwork-git** [comment]
Have you downloaded Bludit from GitHub or with from the the official website:

https://www.bludit.com

**Comment by freaknils** [comment]
I have created the archlinux [PKGBUILD](https://aur.archlinux.org/packages/bludit/) in AUR which downloads it from GitHub (release 2.0.2).

**Comment by clickwork-git** [comment]
Try please with the package from the official website:

https://df6m0u2ovo2fu.cloudfront.net/builds/bludit-v2.0.2.zip

There are some changes in the GitHub that are not yet tested.

**Comment by freaknils** [comment]
Same error like the other version.

**Comment by clickwork-git** [comment]
Can you please PM me the link to the installation or the installation as ZIP archive.

**Comment by dignajar** [comment]
Hi, I tried with Archlinux but I don't match with the issue.

```
# php -v
PHP 7.2.0 (cli) (built: Dec  5 2017 18:56:10) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

```
# nginx -v
nginx version: nginx/1.12.2
```

```
# cat /etc/nginx/nginx.conf 

user http;
worker_processes  1;

error_log  /var/log/nginx/error.log;
error_log  /var/log/nginx/error.log  notice;
error_log  /var/log/nginx/error.log  info;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    index index.php;

    server {
        listen       *:80;
        server_name  localhost;

	root   /usr/share/nginx/html;

	location ~ \.php$ {
		fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
		fastcgi_index index.php;
		root /usr/share/nginx/html;
		include fastcgi.conf;
	}

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
    }
}
```

```
# ps aux | grep php

root      2574  0.0  2.0 190924 21284 ?        Ss   20:22   0:00 php-fpm: master process (/etc/php/php-fpm.conf)
http      2576  0.0  1.5 197936 16080 ?        S    20:22   0:00 php-fpm: pool www
http      2577  0.0  1.5 197936 16080 ?        S    20:22   0:00 php-fpm: pool www
root      2590  0.0  0.2  11708  2056 pts/0    S+   20:24   0:00 grep php
```

```
# ps aux | grep nginx        

root      2581  0.0  0.1  28760  1044 ?        Ss   20:22   0:00 nginx: master process /usr/bin/nginx -g error_log stderr;
http      2582  0.0  0.4  33776  4504 ?        S    20:22   0:00 nginx: worker process
root      2588  0.0  0.2  11708  2164 pts/0    R+   20:24   0:00 grep nginx
```

```
# ls -lrt /usr/share/nginx/html/

total 56
-rw-r--r--  1 http http  2390 Dec 10 21:14 README.md
-rw-r--r--  1 http http  1083 Dec 10 21:14 LICENSE
-rw-r--r--  1 http http 19699 Dec 10 21:14 install.php
-rw-r--r--  1 http http   756 Dec 10 21:14 index.php
drwxr-xr-x 22 http http  4096 Dec 10 21:14 bl-plugins
drwxr-xr-x  2 http http  4096 Dec 10 21:14 bl-languages
drwxr-xr-x  9 http http  4096 Dec 10 21:14 bl-kernel
drwxr-xr-x  2 http http  4096 Dec 11 20:00 bludit-master
drwxr-xr-x  6 http http  4096 Dec 11 20:01 bl-content
drwxr-xr-x  4 http http  4096 Dec 11 20:03 bl-themes
```

**Comment by freaknils** [comment]
So I does not use bludit anymore, I can not try it one more time. Thanks!
